# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DEVS-TOSSIM
author: Guido Marelli
email: rgmarelli@gmail.com
description: A DEVS framework for simulation of TinyOS wireless sensor networks
baseurl: "/devs-tossim" # the subpath of your site, e.g. /blog
url: "http://rgmarelli.github.io/devs-tossim/" # the base hostname & protocol for your site
twitter_username: rgmarelli
github_username:  rgmarelli
linkedin_username: guidomarelli

# Build settings
markdown: kramdown
